config/routes.rb
Rails.application.routes.draw do
  resources :cat_calendars
  resources :calendars
  resources :cats


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calendar.rb
class Calendar < ApplicationRecord
  has_many :cat_calendars

  has_many :cats, through: :cat_calendars
end

app/models/cat.rb
class Cat < ApplicationRecord
  has_many :cat_calendars
  has_many :calendars, through: :cat_calendars
end

app/models/cat_calendar.rb
class CatCalendar < ApplicationRecord
  belongs_to :cat 
  belongs_to :calendar 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController

  def new 
    @calendar = Calendar.new
  end

  def show 
    @calendar = Calendar.find(params[:id])
  end

  def create
    @calendar = Calendar.create(calendar_params)
    redirect_to calendar_path(@calendar)
  end


  private

  def calendar_params
    params.require(:calendar).permit(:title)
  end
end

app/controllers/cat_calendars_controller.rb
class CatCalendarsController < ApplicationController

  def index 
    @cat_calendars = CatCalendar.all
  end

  def new 
    @cat_calendar = CatCalendar.new
    if params[:calendar_id] && params[:month]
      session[:calendar_id] = params[:calendar_id] 
      session[:month] = params[:month]
    end
  end

  # def show 
  #   @cat_calendar = CatCalendar.find(params[:id])
  # end

  def create 
    @cat_calendar = CatCalendar.create(month: session[:month], cat_id: params[:cat_id], calendar_id: session[:calendar_id])
    # redirect_to edit_cat_calendar_path(@cat_calendar.id)
    redirect_to calendar_path(session[:calendar_id])
  end

  def update 
    @cat_calendar = CatCalendar.find(params[:id])
    
    @cat = Cat.find(params[:cat_id])
    @cat_calendar.cat = @cat
    @cat_calendar.save
    redirect_to calendar_path(@cat_calendar.calendar_id)
  end

  # def show 
  #   @cat_calendar = CatCalendar.find(params[:id])
  # end

  def edit 
    @cat_calendar = CatCalendar.find(params[:id])
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index 
    @cats = Cat.all
  end

  def show 
    @cat = Cat.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/cat_calendars_helper.rb
module CatCalendarsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/calendars/new.html.erb
<div class="new_calendar">
<%= form_for @calendar do |f| %>
  <%= f.label :title, "Name Your Calendar!", class: "name_calendar" %>
  <div class="submit"><%= f.text_field :title %></div>

  <div class="submit"><%= f.submit %></div>
<% end %>
</div>

app/views/calendars/show.html.erb
<h1> Calendar Show Page </h1>

<% @cat_month = CatCalendar.find_by(month: "January", calendar_id: @calendar.id) %>
<%= @cat_month ? (button_to "January", edit_cat_calendar_path(@cat_month), method: :get, params: {calendar_id: @calendar.id, month: "January"}) : (button_to "January", new_cat_calendar_path, method: :get, params: {calendar_id: @calendar.id, month: "January"}) %>
<%= image_tag("https://blankcalendarpages.com/printable_calendar/blank-18/January-2020-calendar-b18.jpg", class: "calendar_pic") %>
<%= image_tag(@cat_month.cat.img_url, class: "cat-month-pic") if @cat_month %>

<% @cat_month = CatCalendar.find_by(month: "February", calendar_id: @calendar.id) %>
<%= @cat_month ? (button_to "February", edit_cat_calendar_path(@cat_month), method: :get, params: {calendar_id: @calendar.id, month: "February"}) : (button_to "February", new_cat_calendar_path, method: :get, params: {calendar_id: @calendar.id, month: "February"}) %>
<%= image_tag("https://blankcalendarpages.com/printable_calendar/blank-18/February-2020-calendar-b18.jpg", class: "calendar_pic") %>
<%= image_tag(@cat_month.cat.img_url, class: "cat-month-pic") if @cat_month %>

<% @cat_month = CatCalendar.find_by(month: "March", calendar_id: @calendar.id) %>
<%= @cat_month ? (button_to "March", edit_cat_calendar_path(@cat_month), method: :get, params: {calendar_id: @calendar.id, month: "March"}) : (button_to "March", new_cat_calendar_path, method: :get, params: {calendar_id: @calendar.id, month: "March"}) %>
<%= image_tag("https://blankcalendarpages.com/printable_calendar/blank-18/March-2020-calendar-b18.jpg", class: "calendar_pic") %>
<%= image_tag(@cat_month.cat.img_url, class: "cat-month-pic") if @cat_month %>


<% @cat_month = CatCalendar.find_by(month: "April", calendar_id: @calendar.id) %>
<%= @cat_month ? (button_to "April", edit_cat_calendar_path(@cat_month), method: :get, params: {calendar_id: @calendar.id, month: "April"}) : (button_to "April", new_cat_calendar_path, method: :get, params: {calendar_id: @calendar.id, month: "April"}) %>
<%= image_tag("https://blankcalendarpages.com/printable_calendar/blank-18/April-2020-calendar-b18.jpg", class: "calendar_pic") %>
<%= image_tag(@cat_month.cat.img_url, class: "cat-month-pic") if @cat_month %>

<% @cat_month = CatCalendar.find_by(month: "May", calendar_id: @calendar.id) %>
<%= @cat_month ? (button_to "May", edit_cat_calendar_path(@cat_month), method: :get, params: {calendar_id: @calendar.id, month: "May"}) : (button_to "May", new_cat_calendar_path, method: :get, params: {calendar_id: @calendar.id, month: "May"}) %>
<%= image_tag("https://blankcalendarpages.com/printable_calendar/blank-18/May-2020-calendar-b18.jpg", class: "calendar_pic") %>
<%= image_tag(@cat_month.cat.img_url, class: "cat-month-pic") if @cat_month %>

<% @cat_month = CatCalendar.find_by(month: "June", calendar_id: @calendar.id) %>
<%= @cat_month ? (button_to "June", edit_cat_calendar_path(@cat_month), method: :get, params: {calendar_id: @calendar.id, month: "June"}) : (button_to "June", new_cat_calendar_path, method: :get, params: {calendar_id: @calendar.id, month: "June"}) %>
<%= image_tag("https://blankcalendarpages.com/printable_calendar/blank-18/June-2020-calendar-b18.jpg", class: "calendar_pic") %>
<%= image_tag(@cat_month.cat.img_url, class: "cat-month-pic") if @cat_month %>

<% @cat_month = CatCalendar.find_by(month: "July", calendar_id: @calendar.id) %>
<%= @cat_month ? (button_to "July", edit_cat_calendar_path(@cat_month), method: :get, params: {calendar_id: @calendar.id, month: "July"}) : (button_to "July", new_cat_calendar_path, method: :get, params: {calendar_id: @calendar.id, month: "July"}) %>
<%= image_tag("https://blankcalendarpages.com/printable_calendar/blank-18/July-2020-calendar-b18.jpg", class: "calendar_pic") %>
<%= image_tag(@cat_month.cat.img_url, class: "cat-month-pic") if @cat_month %>

<% @cat_month = CatCalendar.find_by(month: "August", calendar_id: @calendar.id) %>
<%= @cat_month ? (button_to "August", edit_cat_calendar_path(@cat_month), method: :get, params: {calendar_id: @calendar.id, month: "August"}) : (button_to "August", new_cat_calendar_path, method: :get, params: {calendar_id: @calendar.id, month: "August"}) %>
<%= image_tag("https://blankcalendarpages.com/printable_calendar/blank-18/August-2020-calendar-b18.jpg", class: "calendar_pic") %>
<%= image_tag(@cat_month.cat.img_url, class: "cat-month-pic") if @cat_month %>

<% @cat_month = CatCalendar.find_by(month: "September", calendar_id: @calendar.id) %>
<%= @cat_month ? (button_to "September", edit_cat_calendar_path(@cat_month), method: :get, params: {calendar_id: @calendar.id, month: "September"}) : (button_to "September", new_cat_calendar_path, method: :get, params: {calendar_id: @calendar.id, month: "September"}) %>
<%= image_tag("https://blankcalendarpages.com/printable_calendar/blank-18/September-2020-calendar-b18.jpg", class: "calendar_pic") %>
<%= image_tag(@cat_month.cat.img_url, class: "cat-month-pic") if @cat_month %>

<% @cat_month = CatCalendar.find_by(month: "October", calendar_id: @calendar.id) %>
<%= @cat_month ? (button_to "October", edit_cat_calendar_path(@cat_month), method: :get, params: {calendar_id: @calendar.id, month: "October"}) : (button_to "October", new_cat_calendar_path, method: :get, params: {calendar_id: @calendar.id, month: "October"}) %>
<%= image_tag("https://blankcalendarpages.com/printable_calendar/blank-18/October-2020-calendar-b18.jpg", class: "calendar_pic") %>
<%= image_tag(@cat_month.cat.img_url, class: "cat-month-pic") if @cat_month %>

<% @cat_month = CatCalendar.find_by(month: "November", calendar_id: @calendar.id) %>
<%= @cat_month ? (button_to "November", edit_cat_calendar_path(@cat_month), method: :get, params: {calendar_id: @calendar.id, month: "November"}) : (button_to "November", new_cat_calendar_path, method: :get, params: {calendar_id: @calendar.id, month: "November"}) %>
<%= image_tag("https://blankcalendarpages.com/printable_calendar/blank-18/November-2020-calendar-b18.jpg", class: "calendar_pic") %>
<%= image_tag(@cat_month.cat.img_url, class: "cat-month-pic") if @cat_month %>

<% @cat_month = CatCalendar.find_by(month: "December", calendar_id: @calendar.id) %>
<%= @cat_month ? (button_to "December", edit_cat_calendar_path(@cat_month), method: :get, params: {calendar_id: @calendar.id, month: "December"}) : (button_to "December", new_cat_calendar_path, method: :get, params: {calendar_id: @calendar.id, month: "December"}) %>
<%= image_tag("https://blankcalendarpages.com/printable_calendar/blank-18/December-2020-calendar-b18.jpg", class: "calendar_pic") %>
<%= image_tag(@cat_month.cat.img_url, class: "cat-month-pic") if @cat_month %>

app/views/cat_calendars/edit.html.erb
<h1> Edit You Cat Calendar!!!!!!!!!!!!!!!!!!!!!!!!!!!! </h1>


  <% Cat.all.each do |cat| %>
  <%= image_tag(cat.img_url, class: "cat_pic") %>
  <%= button_to cat.id, cat_calendar_path(@cat_calendar.id), method: :patch, params: {cat_id: cat.id} %>
  <%= cat.id %>
<% end %>

app/views/cat_calendars/new.html.erb
<h1> CatCalendar New Page </h1>
<body>


<% Cat.all.each do |cat| %>
  <%= image_tag(cat.img_url, class: "cat_pic") %>
  <%= button_to cat.id, cat_calendars_path, method: :post, params: {cat_id: cat.id} %>
  <%= cat.id %>
<% end %>
</body>

app/views/cats/_form.html.erb
<%= form_for @cat do |f| %>
<%= f.collection_select :id, Cat.all, :id, :id %> 
<%= f.submit "Pick-a-Cat" %>
<% end %>

app/views/cats/index.html.erb
<% @cats.each do |cat| %>
  <%= image_tag(cat.img_url, class: "cat_pic") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CatMemeCalendar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>